PRGS=open2close2
CFLAGS=-ansi -pedantic -Wall -Wextra -Wunreachable-code -Wdeclaration-after-statement -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-declarations -Wmissing-prototypes -Werror

all: $(PRGS)

clean:
	rm -f $(PRGS) *.o *~ *.out
